### ISSUE TITLE
Installation fails due to conflicting Werkzeug version

### ISSUE THREAD

**Issue by NeolithEra** [gingeleski/jawfish#9]
Hi, users are unable to run jawfish due to dependency conflict with _**Werkzeug**_ package. 
As shown in the following full dependency graph of **_jawfish_**, **jawfish** requires _**Werkzeug==0.11.11**_，while **_flask>=0.12.3_** requires _**Werkzeug>=0.15**_.

According to pip’s _“first found wins”_ installation strategy, _**Werkzeug==0.11.11**_ is the actually installed version. However, _**Werkzeug==0.11.11**_ does not satisfy _**Werkzeug>=0.15**_.

### Dependency tree
```
jawfish-master
| +-flask(version range:>=0.12.3)
| | +-click(version range:>=5.1)
| | +-itsdangerous(version range:>=0.24)
| | +-jinja2(version range:>=2.10.1)
| | | +-markupsafe(version range:>=0.23)
| | +-werkzeug(version range:>=0.15)
| +-flask-sslify(version range:==0.1.5)
| | +-flask(version range:*)
| | | +-click(version range:>=5.1)
| | | +-itsdangerous(version range:>=0.24)
| | | +-jinja2(version range:>=2.10.1)
| | | | +-markupsafe(version range:>=0.23)
| | | +-werkzeug(version range:>=0.15)
| +-itsdangerous(version range:==0.24)
| +-jinja2(version range:>=2.10.1)
| | +-markupsafe(version range:>=0.23)
| +-markupsafe(version range:==0.23)
| +-werkzeug(version range:==0.11.11)
| +-wtforms(version range:==2.1)
```

Thanks for your help.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Solution

1.	Fix your direct dependency to be **_Werkzeug>=0.15_**. 
I have checked this revision will not affect your downstream projects now.

2.	Remove your direct dependency **_Werkzeug_**, and use **_Werkzeug_** transitively introduced by flask.

Which solution do you prefer, 1 or 2?

@gingeleski  Please let me know your choice. I can submit a PR to solve this issue.

**Comment by gingeleski** [comment]
2 - thanks.
